#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');
const os = require('os');

function formatTime(isoStr, short = false) {
  if (!isoStr) return '';
  const t = new Date(isoStr).toTimeString().slice(0, 8);
  return short ? t.slice(0, 5) : t;
}

function describeToolUse(block) {
  const { name, input = {} } = block;
  switch (name) {
    case 'Read':  return { icon: '📖', text: `Read \`${path.basename(input.file_path || '')}\`` };
    case 'Write': return { icon: '✏️', text: `Write \`${path.basename(input.file_path || '')}\`` };
    case 'Edit':  return { icon: '✏️', text: `Edit \`${path.basename(input.file_path || '')}\`` };
    case 'Bash':  return { icon: '💻', text: `Bash \`${(input.command || '').slice(0, 80)}\`` };
    case 'Grep':  return { icon: '🔍', text: `Grep \`${input.pattern || ''}\`` };
    case 'Glob':  return { icon: '🔍', text: `Glob \`${input.pattern || ''}\`` };
    case 'Agent': return { icon: '🤖', text: `Agent: ${input.description || input.subagent_type || ''}` };
    default:      return { icon: '🔧', text: name };
  }
}

function cleanUserText(text) {
  let s = text;
  // 슬래시 명령어 태그: <command-name>/plugin</command-name> → /plugin
  s = s.replace(/<command-name>([\s\S]*?)<\/command-name>/g, (_, v) => v.trim());
  // 나머지 command 메타 태그 제거
  s = s.replace(/<command-message>[\s\S]*?<\/command-message>/g, '');
  s = s.replace(/<command-args>[\s\S]*?<\/command-args>/g, '');
  s = s.replace(/<local-command-stdout>[\s\S]*?<\/local-command-stdout>/g, '');
  s = s.replace(/<system-reminder>[\s\S]*?<\/system-reminder>/g, '');
  // 기타 남은 태그 제거
  s = s.replace(/<[^>]+>/g, '');
  return s.replace(/\s+/g, ' ').trim() || text.trim();
}

// 시스템이 자동 삽입하는 메시지 패턴 — 유저 질문이 아니므로 통째로 건너뜀
const SYSTEM_SKIP_PATTERNS = [
  /^Caveat: The messages below were generated by the user while running local commands/i,
  /^This session is being continued from a previous conversation that ran out of context/i,
];

function extractUserText(content) {
  if (typeof content === 'string') return content.trim();
  if (!Array.isArray(content)) return '';

  const textBlocks = content.filter(c => c.type === 'text' && c.text?.trim());

  // Case 1: 슬래시 명령어 → <command-name> 태그가 있는 블록 처리
  const commandBlocks = textBlocks.filter(c => c.text.includes('<command-name>'));
  if (commandBlocks.length > 0) {
    // 스킬 문서 블록에 "## User Request" 섹션이 있으면 실제 요청만 추출
    const nonCommandBlocks = textBlocks.filter(c => !c.text.includes('<command-name>'));
    for (const block of nonCommandBlocks) {
      const match = block.text.match(/##\s*User\s*Request\s*\n([\s\S]+?)(?=\n##\s|\s*$)/i);
      if (match) return match[1].trim();
    }
    return commandBlocks.map(c => c.text.trim()).join('\n\n');
  }

  // Case 2: 스킬 문서 직접 삽입 ("Base directory for this skill:" 로 시작하는 블록)
  const nonSkillBlocks = textBlocks.filter(
    c => !c.text.trimStart().startsWith('Base directory for this skill:')
  );
  // 유저 텍스트가 있는 블록만 사용, 없으면 null 반환(건너뜀)
  return nonSkillBlocks.length > 0
    ? nonSkillBlocks.map(c => c.text.trim()).filter(Boolean).join('\n\n')
    : null;
}

function groupIntoTurns(records) {
  const turns = [];
  let cur = null;

  for (const rec of records) {
    if (rec.type === 'user' && rec.message?.role === 'user') {
      const content = rec.message.content;
      const hasText = typeof content === 'string'
        ? content.trim().length > 0
        : Array.isArray(content) && content.some(c => c.type === 'text' && c.text?.trim());
      if (!hasText) continue;

      const rawText = extractUserText(content);
      if (rawText === null) continue; // 순수 스킬 문서 블록, 건너뜀

      const userText = cleanUserText(rawText);
      if (!userText) continue;

      // 시스템 자동 삽입 메시지 건너뜀
      if (SYSTEM_SKIP_PATTERNS.some(p => p.test(userText))) continue;

      cur = { index: turns.length + 1, timestamp: rec.timestamp, userText, parts: [] };
      turns.push(cur);

    } else if (rec.type === 'assistant' && rec.message?.role === 'assistant' && cur) {
      for (const block of (rec.message.content || [])) {
        if (block.type === 'text' && block.text?.trim()) {
          cur.parts.push({ type: 'text', content: block.text.trim() });
        } else if (block.type === 'tool_use') {
          cur.parts.push({ type: 'tool', name: block.name, ...describeToolUse(block) });
        }
      }
    }
  }

  return turns.filter(t => t.userText);
}

function buildFull(turns, sessionId, sessionStart) {
  const sections = turns.map(turn => {
    const ts = formatTime(turn.timestamp);
    const tools = turn.parts.filter(p => p.type === 'tool');
    const texts = turn.parts.filter(p => p.type === 'text');

    // 유저 메시지: blockquote 박스 + 라벨 + 굵은 글씨
    const userBoxLines = turn.userText.split('\n').map(l => `> ${l}`).join('\n');

    let block = `### #${turn.index} · ${ts}\n\n`;
    block += `> 👤 **User**\n>\n${userBoxLines}\n\n`;
    block += `🤖 **Claude**\n\n`;
    if (tools.length > 0) block += tools.map(t => `- ${t.icon} ${t.text}`).join('\n') + '\n\n';
    if (texts.length > 0) block += texts.map(t => t.content).join('\n\n');
    return block.trimEnd();
  });

  return `## Session \`${sessionId.slice(0, 8)}\` — ${sessionStart}\n\n` +
    sections.join('\n\n---\n\n');
}

function findTranscript(sessionId) {
  try {
    const root = path.join(os.homedir(), '.claude', 'projects');
    for (const dir of fs.readdirSync(root)) {
      const p = path.join(root, dir, sessionId + '.jsonl');
      if (fs.existsSync(p)) return p;
    }
  } catch {}
  return null;
}

let raw = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', c => raw += c);
process.stdin.on('end', () => {
  try {
    const data = JSON.parse(raw || '{}');
    const { session_id: sessionId, transcript_path } = data;
    if (!sessionId) process.exit(0);

    const transcriptPath = transcript_path || findTranscript(sessionId);
    if (!transcriptPath || !fs.existsSync(transcriptPath)) process.exit(0);

    const records = fs.readFileSync(transcriptPath, 'utf8')
      .split('\n').filter(Boolean)
      .map(l => { try { return JSON.parse(l); } catch { return null; } })
      .filter(Boolean);
    if (!records.length) process.exit(0);

    let projectDir = null;
    for (const r of records) { if (r.cwd) { projectDir = r.cwd; break; } }
    if (!projectDir) process.exit(0);

    const turns = groupIntoTurns(records);
    if (!turns.length) process.exit(0);

    const projectName = path.basename(projectDir);
    const date = new Date().toISOString().split('T')[0];
    const sessionStart = records.find(r => r.timestamp)?.timestamp || new Date().toISOString();
    const logsDir = path.join(projectDir, '.claude', 'session-logs');
    fs.mkdirSync(logsDir, { recursive: true });

    const fullPath = path.join(logsDir, `${projectName}-${date}.md`);
    const newBody = buildFull(turns, sessionId, sessionStart);
    const marker = `## Session \`${sessionId.slice(0, 8)}\``;

    if (!fs.existsSync(fullPath)) {
      fs.writeFileSync(fullPath, `# ${projectName} — ${date}\n\n${newBody}`, 'utf8');
    } else {
      let content = fs.readFileSync(fullPath, 'utf8');
      const idx = content.indexOf(marker);
      if (idx === -1) {
        // 이 세션이 파일에 없으면 append
        fs.writeFileSync(fullPath, content.trimEnd() + '\n\n---\n\n' + newBody, 'utf8');
      } else {
        // 이 세션 블록이 이미 있으면 교체 (중복 방지)
        const rest = content.slice(idx);
        const nextMatch = rest.match(/\n\n---\n\n## Session/);
        const blockLen = nextMatch ? nextMatch.index : rest.length;
        content = content.slice(0, idx) + newBody + content.slice(idx + blockLen);
        fs.writeFileSync(fullPath, content, 'utf8');
      }
    }

  } catch {}
  process.exit(0);
});